version: "3"

services:
  mongodb:
    container_name: tok_tg_mongodb
    image: 'mongo:latest'
    
    ports:
      - 127.0.0.1:${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
  
  tok_tg_bot:
    container_name: tok_tg_bot
    command: go run .
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongodb
