version: "3"

services:
  mongodb:
    container_name: tok_tg_mongodb
    image: 'mongo:latest'
    ports:
      - 127.0.0.1:${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
    networks:
      - app_network
    
  tok_api:
    container_name: tok_api
    restart: always
    ports:
      - 127.0.0.1:${API_PORT:-8001}:${API_PORT:-8001}
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    depends_on:
      - mongodb
    networks:
      - app_network
  
  nginx:
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - tok_api
    networks:
      - app_network

  tok_tg_bot:
    container_name: tok_tg_bot
    restart: always
    build:
      context: .
      dockerfile: cmd/bot/Dockerfile
    depends_on:
      - mongodb
    networks:
      - app_network

networks:
  app_network:
    driver: bridge