version: "3"

services:
  # mongodb:
  #   container_name: tok_tg_mongodb
  #   image: 'mongo:latest'
  #   ports:
  #     - 127.0.0.1:${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}
  #   volumes:
  #     - ${MONGODB_PATH:-./mongodb}:/data/db
    
  tok_api:
    container_name: tok_api
    restart: always
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    # depends_on:
    #   - mongodb
  
  tok_tg_bot:
    container_name: tok_tg_bot
    restart: always
    build:
      context: .
      dockerfile: cmd/bot/Dockerfile
    # depends_on:
    #   - mongodb
